baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hello world"
theme = "friend"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Uniqued development"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "www.Uniqued.eu test page"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "O FIRMIE"
    url        = "about/"
  [[menu.main]]
    identifier = "offer"
    name       = "OFERTA"
    url        = "offer/"
  [[menu.main]]
    identifier = "realizations"
    name       = "REALIZACJE"
    url        = "about/"
  [[menu.main]]
    identifier = "immovables"
    name       = "NIERUCHOMOŚCI"
    url        = "immovables/"
  [[menu.main]]
    identifier = "contact"
    name       = "KONTAKT"
    url        = "contact/"
